version: "3"
services:
  website:
    image: nginx
    ports:
      - "8081:80"
    restart: always
  website3:
    image: nginx
    ports:
      - "8083:80"
    restart: always
    networks:
     coffee:
       ipv4_address: 192.168.92.21
networks:
  coffee:
    ipam:
      driver: default
      config:
        - subnet: "192.168.92.0/24"
